---
- name: converge

  hosts: all

  become: true

  pre_tasks:

    - name: update apt cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'

  roles:

    - nephelaiio.avideo
