---
- name: converge

  hosts: all

  become: true

  pre_tasks:

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: false

    - name: create backup path
      ansible.builtin.file:
        dest: "{{ avideo_backup_path }}"
        state: directory
        mode: 0750

  roles:

    - nephelaiio.avideo
