---
- name: verify

  hosts: all

  gather_facts: false

  tasks:

    - name: verify avideo front page
      ansible.builtin.uri:
        url: "https://{{ avideo_servername }}"
        return_content: true
        validate_certs: false
      register: uri_query
      failed_when: avideo_site_title not in uri_query.content
