---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE__DOCKER_DISTRO:-ubuntu2004}-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_IMAGE_COMMAND:-"/lib/systemd/systemd"}
    pre_build_image: true
    privileged: true
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  inventory:
    host_vars:
      instance:
        avideo_debug: true
        avideo_servername: localhost
        avideo_site_title: this_is_a_test
        avideo_mysql_root_user: root
        avideo_mysql_root_pass: root
        avideo_db_user: "{{ avideo_mysql_root_user }}"
        avideo_db_pass: "{{ avideo_mysql_root_pass }}"
        avideo_db_user_manage: false
        avideo_tls_certificate: " /etc/ssl/certs/ssl-cert-snakeoil.pem"
        avideo_tls_cert_key: "/etc/ssl/private/ssl-cert-snakeoil.key"
verifier:
  name: ansible
