---
name: molecule

on:
  pull_request:
  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: 'nephelaiio.avideo'

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.avideo'

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install test dependencies
        run: poetry install

      - name: lint code
        run: |
          poetry run yamllint .
          poetry run ansible-lint . -c .ansible-lint.yml

  molecule:
    name: molecule tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
          - users
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: ubuntu2004
            command: /lib/systemd/systemd

    steps:

      - name: check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.avideo'

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: run molecule tests
        run: poetry run molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.image.name }}
          MOLECULE_COMMAND: ${{ matrix.image.command }}
